version: '3.8'

services:
  hugo:
    image: ${HUGO_IMAGE}
    command: server --bind 0.0.0.0 --buildDrafts --buildFuture
    ports:
      - "1313:1313"
    volumes:
      - ./src/emanueletessore.com:/src
    working_dir: /src
    environment:
      - HUGO_REFRESH_TIME=1
      - HUGO_THEME=careercanvas
    networks:
      - hugo-network

  hugo-build:
    image: ${HUGO_IMAGE}
    command: --minify
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - HUGO_THEME=careercanvas
    profiles:
      - build

networks:
  hugo-network:
    driver: bridge
