version: "3"

dotenv:
  - .env

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  hugo:
    desc: Run Hugo commands
    cmds:
      - docker run
        --rm
        --name hugo
        --user $(id -u):$(id -g)
        --publish 1313:1313
        --volume .:/src
        --workdir /src/src/emanueletessore.com
        --env HUGO_THEME
        ${HUGO_IMAGE}
        {{.CLI_ARGS}}

  hugo:serve:
    desc: Start Hugo development server
    cmds:
      - task: hugo
        vars:
          CLI_ARGS: server --bind 0.0.0.0

  hugo:serve-drafts:
    desc: Start Hugo development server including drafts
    cmds:
      - task: hugo
        vars:
          CLI_ARGS: server --bind 0.0.0.0 --buildDrafts --buildFuture

  hugo:build:
    desc: Build static site for production
    cmds:
      - task: hugo
        vars:
          CLI_ARGS: build

  hugo:lint:
    desc: Lint Hugo configuration and content
    cmds:
      - task: hugo
        vars:
          CLI_ARGS: check

  npm:
    desc: Run npm commands
    cmds:
      - docker run
        --rm
        --name npm
        --user $(id -u):$(id -g)
        --volume .:/src
        --workdir /src/src/emanueletessore.com
        node
        npm {{.CLI_ARGS}}

  clean:
    desc: Clean generated files
    cmds:
      - rm -fr src/emanueletessore.com/public/
      - rm -fr src/emanueletessore.com/resources/
      - rm -fr src/emanueletessore.com/node_modules/

  update-theme:
    desc: Update theme to latest version
    cmds:
      - git submodule update --init --recursive

  stop:
    desc: Stop all services
    cmds:
      - docker rm -f hugo || true
