baseURL: https://www.emanueletessore.com
languageCode: en-us
title: Emanuele Tessore
theme: careercanvas
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true
summaryLength: 30
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github-dark
    lineNos: false
    # noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: "line"
    lineNoStart: 1
    # lineNos: false
    lineNumbersInTable: true
    noClasses: true
    # style: monokai
    tabWidth: 2
    wrapperClass: highlight
menu:
  main:
    # - name: Home
    #   url: /
    #   weight: 10
    - name: About
      url: /#about
      weight: 20
    - name: Skills
      url: /#skills
      weight: 30
    - name: Experience
      url: /#experience
      weight: 40
    - name: Techstack
      url: /#technical
      weight: 50
    - name: Contact
      url: /#contact
      weight: 60
    # - name: Projects
    #   url: /projects/
    #   weight: 70
    - name: Docs
      url: /docs/
      weight: 80
params:
  author: Emanuele Tessore
  profile_image: /images/emanuele-tex-tessore.png
  fourofour_image: /images/404-afraid.png
  tagline: DevOps, WebDev & Tech Enthusiast
  keywords:
    - DevOps
    - Web Developer
    - Kubernetes
    - Linux
    - Open Source
    - Tech
  name: Emanuele Tessore
  nickname: Tex / Setola
  profession: DevOps Engineer
  location: Venice, Italy
  email: me@emanueletessore.com
  formspree_endpoint: https://formspree.io/f/mqabozwr
  github_url: https://github.com/setola
  github_text: Setola on Github
  resume_url_en: https://docs.google.com/document/d/1I-fZ6CrUhZ_fn8XalgClz-EFNdPUl5-SOTSK_j563AY/export?format=pdf&tab=t.0
  resume_url_it: https://docs.google.com/document/d/1yD2uu7ZjBKukheOU8FdjV56QBqPd4qW03gdThYb5tlA/export?format=pdf&tab=t.0
  resume_label: Resume
  copyright: © 2025 | Emanuele Tessore
  social:
    - name: "Github"
      url: "https://github.com/setola"
      icon: "fa fa-github fa-2x github"
      weight: 10
    # - name: "Linkedin"
    #   icon: "fa fa-linkedin fa-2x linkedin"
    #   url: "https://www.linkedin.com/in/emanuele-tessore-02706924/"
    #   weight: 20
    - name: "bitbucket"
      icon: "fa fa-bitbucket fa-2x"
      url: "https://bitbucket.org/setola/"
      weight: 30
    - name: "telegram"
      icon: "fa fa-telegram fa-2x telegram"
      url: "https://telegram.me/Setola"
      weight: 50
    - name: "whatsapp"
      icon: "fa fa-whatsapp fa-2x whatsapp"
      url: "https://wa.me/+393934227139"
      weight: 60
  pexels:
    queries:
      - universe solar systems nasa pictures
      - structural long span bridges
      - nebula nasa pictures
  color_palettes:
    palette:
      - name: professional
        main_color: "#474A51"
        second_color: "#E52521"
        third_color: "#3CB043"
      # - name: ocean
      #   main_color: "#1E40AF"
      #   second_color: "#06B6D4"
      #   third_color: "#10B981"
      # - name: sunset
      #   main_color: "#DC2626"
      #   second_color: "#F59E0B"
      #   third_color: "#EF4444"
      # - name: forest
      #   main_color: "#059669"
      #   second_color: "#10B981"
      #   third_color: "#F59E0B"
      # - name: fire
      #   main_color: "#EA580C"
      #   second_color: "#DC2626"
      #   third_color: "#F59E0B"
      # - name: steel
      #   main_color: "#374151"
      #   second_color: "#6B7280"
      #   third_color: "#10B981"
      # - name: navy
      #   main_color: "#1E3A8A"
      #   second_color: "#3B82F6"
      #   third_color: "#F59E0B"
      # - name: charcoal
      #   main_color: "#1F2937"
      #   second_color: "#EF4444"
      #   third_color: "#22C55E"
      # - name: slate
      #   main_color: "#475569"
      #   second_color: "#0EA5E9"
      #   third_color: "#F97316"
      # - name: midnight
      #   main_color: "#0F172A"
      #   second_color: "#8B5CF6"
      #   third_color: "#06B6D4"
outputs:
  home:
    - HTML
    - JSON
    - RSS
  section:
    - HTML
    - JSON
build:
  writeStats: true
security:
  enableInlineShortcodes: false
  exec:
    allow:
      - ^(dart-)?sass(-embedded)?$
      - ^go$
      - ^npx$
      - ^postcss$
      - git
    osEnv:
      - (?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_)?CACHE_HOME|YARN_CACHE_FOLDER)$
  funcs:
    getenv:
      - ^HUGO_
      - ^CI$
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*
languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 1
    params:
      tagline: DevOps. Coder. Problem Solver.
      description: Make the world a better place, one line of code at a time!
      hero_description: >
        Make the world a better place, one line of code at a time!
      hero_location: Venice, Italy  
      collab_tags:
        - DevOps Manager
        - Cybersecurity Specialist
        - Cloud Architect
        - IT Consultant
        - R&D and Innovation
        - Kubernetes Expert
        - Open Source Advocate
        - Automation Specialist

    hero:
      title: Hi! I'm Emanuele
      subtitle: but everybody calls me Tex or Setola
      description:
        I'm a DevOps engineer, I was a web developer and I'll forever be a
        tech enthusiast.
      image: /images/profile.jpg
