name: Makefile CI

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
        - name: Checkout 
          uses: actions/checkout@main
        - uses: actions/setup-node@main
        - run: ( cd src/emanueletessore.com/ && npm install )
        - run: docker run --user $(id -u):$(id -g) --rm --volume ${{ github.workspace }}:/src --workdir /src/src/emanueletessore.com hugomods/hugo:debian-ci-non-root build --verbose
        - run: ls -la src/emanueletessore.com/public
        - name: Setup Pages
          uses: actions/configure-pages@main
        - name: Upload artifact
          uses: actions/upload-pages-artifact@main
          with:
            path: './src/emanueletessore.com/public'
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@main